# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8b0f7836-9db0-49d8-aade-2ef1d1af37ce";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/21CB-F688";
      fsType = "vfat";
    };

  fileSystems."/wayfarer" =
    { device = "/dev/disk/by-uuid/604bb906-14a3-4e90-825e-c28ad22bc38f";
      fsType = "ext4";
    };

  swapDevices = [ ];

}
